-- 더미 데이터

-- 회원
INSERT INTO MEMBER (NO,NAME,ID,PWD,DONG_NUM,HO_NUM,BIRTH,PHONE,EMAIL,PROFILE,GRADE) VALUES (SEQ_MEMBER_NO.NEXTVAL, '김하나' , 'USER01' , '1111' , '101', '101', '19790111', '01012341234', 'k0322123@gmail.com', '뚱이.jpg' ,'Y');
INSERT INTO MEMBER (NO,NAME,ID,PWD,DONG_NUM,HO_NUM,BIRTH,PHONE,EMAIL,PROFILE) VALUES (SEQ_MEMBER_NO.NEXTVAL, '이하다' , 'USER02' ,'2222' , '101', '101', '19790222', '01012351235', 'k0322124@gmail.com', '치삼제.jpg' );
INSERT INTO MEMBER (NO,NAME,ID,PWD,DONG_NUM,HO_NUM,BIRTH,PHONE,EMAIL) VALUES (SEQ_MEMBER_NO.NEXTVAL, '김하랑' , 'USER03' ,'3333' , '101', '101', '20080306', '01012351235', 'k0322124@gmail.com' );
INSERT INTO MEMBER (NO,NAME,ID,PWD,DONG_NUM,HO_NUM,BIRTH,PHONE,EMAIL) VALUES (SEQ_MEMBER_NO.NEXTVAL, '김하정' , 'USER04' ,'4444' , '101', '101', '2009520', '01012351235', 'k0322124@gmail.com' );
INSERT INTO MEMBER (NO,NAME,ID,PWD,DONG_NUM,HO_NUM,BIRTH,PHONE,EMAIL) VALUES (SEQ_MEMBER_NO.NEXTVAL, '박수민' , 'USER05' ,'5555' , '102', '1101', '19880111', '01012361236', 'k0322125@gmail.com' );
INSERT INTO MEMBER (NO,NAME,ID,PWD,DONG_NUM,HO_NUM,BIRTH,PHONE,EMAIL) VALUES (SEQ_MEMBER_NO.NEXTVAL, '김경민' , 'USER06' ,'6666' , '102', '1101', '19890222', '01012371237', 'k0322126@gmail.com' );
INSERT INTO MEMBER (NO,NAME,ID,PWD,DONG_NUM,HO_NUM,BIRTH,PHONE,EMAIL) VALUES (SEQ_MEMBER_NO.NEXTVAL, '김수현' , 'USER07' ,'7777' , '102', '1101', '20160322', '01012371237', 'k0322124@gmail.com' );
INSERT INTO MEMBER (NO,NAME,ID,PWD,DONG_NUM,HO_NUM,BIRTH,PHONE,EMAIL) VALUES (SEQ_MEMBER_NO.NEXTVAL, '김수혁' , 'USER08' ,'8888' , '102', '1101', '20170630', '01012351235', 'k0322124@gmail.com' );
INSERT INTO MEMBER (NO,NAME,ID,PWD,DONG_NUM,HO_NUM,BIRTH,PHONE,EMAIL) VALUES (SEQ_MEMBER_NO.NEXTVAL, '황정연' , 'USER09' ,'9999' , '103', '1201', '19910404', '01066065505', 'primeum8@naver.com' );
INSERT INTO MEMBER (NO,NAME,ID,PWD,DONG_NUM,HO_NUM,BIRTH,PHONE,EMAIL) VALUES (SEQ_MEMBER_NO.NEXTVAL, '손수정' , 'USER10' ,'1000' , '103', '1201', '19870606', '01077078808', 'primeum9@naver.com' );
INSERT INTO MEMBER (NO,NAME,ID,PWD,DONG_NUM,HO_NUM,BIRTH,PHONE,EMAIL) VALUES (SEQ_MEMBER_NO.NEXTVAL, '이광천' , 'USER11' ,'1100' , '201', '1502', '19680606', '01045132566', 'primeum11@naver.com' );
INSERT INTO MEMBER (NO,NAME,ID,PWD,DONG_NUM,HO_NUM,BIRTH,PHONE,EMAIL) VALUES (SEQ_MEMBER_NO.NEXTVAL, '박민철' , 'USER12' ,'1200' , '301', '803', '19590606', '01077042559', 'primeum12@naver.com' );
INSERT INTO MEMBER (NO,NAME,ID,PWD,DONG_NUM,HO_NUM,BIRTH,PHONE,EMAIL) VALUES (SEQ_MEMBER_NO.NEXTVAL, '신상영' , 'USER13' ,'1300' , '101', '1603', '19600606', '01077062650', 'primeum13@naver.com' );
INSERT INTO MEMBER (NO,NAME,ID,PWD,DONG_NUM,HO_NUM,BIRTH,PHONE,EMAIL) VALUES (SEQ_MEMBER_NO.NEXTVAL, '박지영' , 'USER14' , '1400' , '101', '303', '19830116', '01015475588', 'primeum14@naver.com' );
INSERT INTO MEMBER (NO,NAME,ID,PWD,DONG_NUM,HO_NUM,BIRTH,PHONE,EMAIL) VALUES (SEQ_MEMBER_NO.NEXTVAL, '이서희' , 'USER15' , '1500' , '101', '402', '19840228', '01014558789', 'primeum15@naver.com' );


-- 관리자
INSERT INTO ADMIN (NO,ID,PWD, NAME, GRADE, PROFILE) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN01' , '1111' ,'관리소장', 'M', 'Security.png' );
INSERT INTO ADMIN (NO,ID,PWD, NAME, GRADE, PROFILE) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN02' , '2222' ,'101동 경비원', 'S', 'Security.png' );
INSERT INTO ADMIN (NO,ID,PWD, NAME, GRADE, PROFILE) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN03' , '3333' ,'102동 경비원', 'S', 'Security.png' );
INSERT INTO ADMIN (NO,ID,PWD, NAME, GRADE, PROFILE) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN04' , '4444' ,'103동 경비원', 'S', 'Security.png' );
INSERT INTO ADMIN (NO,ID,PWD, NAME, GRADE, PROFILE) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN05' , '5555' ,'104동 경비원', 'S', 'Security.png' );
INSERT INTO ADMIN (NO,ID,PWD, NAME, GRADE, PROFILE) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN06' , '6666' ,'201동 경비원', 'S', 'Security.png' );
INSERT INTO ADMIN (NO,ID,PWD, NAME, GRADE, PROFILE) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN07' , '7777' ,'202동 경비원', 'S', 'Security.png' );
INSERT INTO ADMIN (NO,ID,PWD, NAME, GRADE, PROFILE) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN08' , '8888' ,'203동 경비원', 'S', 'Security.png' );
INSERT INTO ADMIN (NO,ID,PWD, NAME, GRADE, PROFILE) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN09' , '9999' ,'204동 경비원', 'S', 'Security.png' );
INSERT INTO ADMIN (NO,ID,PWD, NAME, GRADE, PROFILE) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN10' , '1010' ,'301동 경비원', 'S', 'Security.png' );
INSERT INTO ADMIN (NO,ID,PWD, NAME, GRADE, PROFILE) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN11' , '1110' ,'201동대표', 'D', 'Security.png' );
INSERT INTO ADMIN (NO,ID,PWD, NAME, GRADE, PROFILE) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN12' , '1120' ,'301동대표', 'D', 'Security.png' );
INSERT INTO ADMIN (NO,ID,PWD, NAME, GRADE, PROFILE) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'ADMIN13' , '1130' ,'101동대표', 'D', 'Security.png' );


-- 가계부 카테고리 외식
INSERT INTO ACCOUNT_CATEGORY (NO, NAME) VALUES (SEQ_ACCOUNT_CATEGORY_NO.NEXTVAL, '금융/보험');
INSERT INTO ACCOUNT_CATEGORY (NO, NAME) VALUES (SEQ_ACCOUNT_CATEGORY_NO.NEXTVAL, '생활/마트');
INSERT INTO ACCOUNT_CATEGORY (NO, NAME) VALUES (SEQ_ACCOUNT_CATEGORY_NO.NEXTVAL, '의료/건강');
INSERT INTO ACCOUNT_CATEGORY (NO, NAME) VALUES (SEQ_ACCOUNT_CATEGORY_NO.NEXTVAL, '문화/예술');
INSERT INTO ACCOUNT_CATEGORY (NO, NAME) VALUES (SEQ_ACCOUNT_CATEGORY_NO.NEXTVAL, '경조사/회비');
INSERT INTO ACCOUNT_CATEGORY (NO, NAME) VALUES (SEQ_ACCOUNT_CATEGORY_NO.NEXTVAL, '교통/차량');
INSERT INTO ACCOUNT_CATEGORY (NO, NAME) VALUES (SEQ_ACCOUNT_CATEGORY_NO.NEXTVAL, '뷰티/미용');
INSERT INTO ACCOUNT_CATEGORY (NO, NAME) VALUES (SEQ_ACCOUNT_CATEGORY_NO.NEXTVAL, '기타지출');


-- 가계부
INSERT INTO ACCOUNT (NO,WRITER_NO,ACCOUNT_CNO,CONTENT,PRICE,ACCOUNT_DATE) VALUES (SEQ_ACCOUNT_NO.NEXTVAL, '10', '2', '롯데슈퍼 저녁 장', '-24000', '2023-06-01');
INSERT INTO ACCOUNT (NO,WRITER_NO,ACCOUNT_CNO,CONTENT,PRICE,ACCOUNT_DATE) VALUES (SEQ_ACCOUNT_NO.NEXTVAL, '10', '3', '우리이비인후과', '-5500', '2023-06-02');
INSERT INTO ACCOUNT (NO,WRITER_NO,ACCOUNT_CNO,CONTENT,PRICE,ACCOUNT_DATE) VALUES (SEQ_ACCOUNT_NO.NEXTVAL, '10', '2', '한살림 점심 장', '-13000', '2023-06-02');
INSERT INTO ACCOUNT (NO,WRITER_NO,ACCOUNT_CNO,CONTENT,PRICE,ACCOUNT_DATE) VALUES (SEQ_ACCOUNT_NO.NEXTVAL, '10', '7', '올리브영 세일: 토너, 앰플', '-33000', '2023-06-03');
INSERT INTO ACCOUNT (NO,WRITER_NO,ACCOUNT_CNO,CONTENT,PRICE,ACCOUNT_DATE) VALUES (SEQ_ACCOUNT_NO.NEXTVAL, '10', '4', '밀리의 서재', '-9900', '2023-06-03');
INSERT INTO ACCOUNT (NO,WRITER_NO,ACCOUNT_CNO,CONTENT,PRICE,ACCOUNT_DATE) VALUES (SEQ_ACCOUNT_NO.NEXTVAL, '10', '2', '외식:대한닭발', '-30000', '2023-06-03');
INSERT INTO ACCOUNT (NO,WRITER_NO,ACCOUNT_CNO,CONTENT,PRICE,ACCOUNT_DATE) VALUES (SEQ_ACCOUNT_NO.NEXTVAL, '5', '2', '홈플러스 장: 닭고기, 닭볶음탕 양념', '-10000', '2023-06-04');
INSERT INTO ACCOUNT (NO,WRITER_NO,ACCOUNT_CNO,CONTENT,PRICE,ACCOUNT_DATE) VALUES (SEQ_ACCOUNT_NO.NEXTVAL, '5', '5', '지은 결혼식', '-100000', '2023-06-05');
INSERT INTO ACCOUNT (NO,WRITER_NO,ACCOUNT_CNO,CONTENT,PRICE,ACCOUNT_DATE) VALUES (SEQ_ACCOUNT_NO.NEXTVAL, '5', '5', '독서모임 회비', '-15000', '2023-06-15');
INSERT INTO ACCOUNT (NO,WRITER_NO,ACCOUNT_CNO,CONTENT,PRICE,ACCOUNT_DATE) VALUES (SEQ_ACCOUNT_NO.NEXTVAL, '5', '6', '교통카드 한 달', '-110000', '2023-06-15');

INSERT INTO ACCOUNT (NO,WRITER_NO,ACCOUNT_CNO,CONTENT,PRICE,ACCOUNT_DATE) VALUES (SEQ_ACCOUNT_NO.NEXTVAL, '5', '3', '밀리의 서재', '-9900', '2023-07-03');
INSERT INTO ACCOUNT (NO,WRITER_NO,ACCOUNT_CNO,CONTENT,PRICE,ACCOUNT_DATE) VALUES (SEQ_ACCOUNT_NO.NEXTVAL, '5', '2', '외식:대한닭발', '-30000', '2023-07-04');
INSERT INTO ACCOUNT (NO,WRITER_NO,ACCOUNT_CNO,CONTENT,PRICE,ACCOUNT_DATE) VALUES (SEQ_ACCOUNT_NO.NEXTVAL, '5', '1', '홈플러스 장: 닭고기, 닭볶음탕 양념', '-10000', '2023-07-10');
INSERT INTO ACCOUNT (NO,WRITER_NO,ACCOUNT_CNO,CONTENT,PRICE,ACCOUNT_DATE) VALUES (SEQ_ACCOUNT_NO.NEXTVAL, '5', '5', '지은 결혼식', '-100000', '2023-07-15');
INSERT INTO ACCOUNT (NO,WRITER_NO,ACCOUNT_CNO,CONTENT,PRICE,ACCOUNT_DATE) VALUES (SEQ_ACCOUNT_NO.NEXTVAL, '5', '8', '독서모임 회비', '-15000', '2023-07-21');
INSERT INTO ACCOUNT (NO,WRITER_NO,ACCOUNT_CNO,CONTENT,PRICE,ACCOUNT_DATE) VALUES (SEQ_ACCOUNT_NO.NEXTVAL, '5', '9', '돼지저금통 수입' , '110000', '2023-07-19');
INSERT INTO ACCOUNT (NO,WRITER_NO,ACCOUNT_CNO,CONTENT,PRICE,ACCOUNT_DATE) VALUES (SEQ_ACCOUNT_NO.NEXTVAL, '5', '4', '홈플러스 장: 닭고기, 닭볶음탕 양념', '-10000', '2023-07-09');
INSERT INTO ACCOUNT (NO,WRITER_NO,ACCOUNT_CNO,CONTENT,PRICE,ACCOUNT_DATE) VALUES (SEQ_ACCOUNT_NO.NEXTVAL, '5', '4', '지은 결혼식', '-100000', '2023-07-07');
INSERT INTO ACCOUNT (NO,WRITER_NO,ACCOUNT_CNO,CONTENT,PRICE,ACCOUNT_DATE) VALUES (SEQ_ACCOUNT_NO.NEXTVAL, '5', '5', '독서모임 회비', '-15000', '2023-07-16');
INSERT INTO ACCOUNT (NO,WRITER_NO,ACCOUNT_CNO,CONTENT,PRICE,ACCOUNT_DATE) VALUES (SEQ_ACCOUNT_NO.NEXTVAL, '5', '6', '교통카드 한 달', '-110000', '2023-07-20');


-- 회원 캘린더
INSERT INTO MEMBER_CALENDAR (NO,WRITER_NO,NAME,START_DATE,END_DATE,LOVE) VALUES (SEQ_MEMBER_CALENDAR_NO.NEXTVAL, '1', '가정의학과 방문 예정', '2023-08-28','2023-08-29', 'Y');
INSERT INTO MEMBER_CALENDAR (NO,WRITER_NO,NAME,START_DATE,END_DATE,LOVE) VALUES (SEQ_MEMBER_CALENDAR_NO.NEXTVAL, '1', '가족 소풍', '2023-06-30','2023-06-30', 'Y');
INSERT INTO MEMBER_CALENDAR (NO,WRITER_NO,NAME,START_DATE,END_DATE,LOVE) VALUES (SEQ_MEMBER_CALENDAR_NO.NEXTVAL, '1', '미영이네 집들이', '2023-07-01','2023-07-01', 'Y');
INSERT INTO MEMBER_CALENDAR (NO,WRITER_NO,NAME,START_DATE,END_DATE,LOVE) VALUES (SEQ_MEMBER_CALENDAR_NO.NEXTVAL, '1', '수혁이 공개수업', '2023-08-02','2023-08-02', 'Y');
INSERT INTO MEMBER_CALENDAR (NO,WRITER_NO,NAME,START_DATE,END_DATE,LOVE) VALUES (SEQ_MEMBER_CALENDAR_NO.NEXTVAL, '1', '고등학교 동창 캠핑', '2023-06-25','2023-06-29', 'Y');
INSERT INTO MEMBER_CALENDAR (NO,WRITER_NO,NAME,START_DATE,END_DATE,LOVE) VALUES (SEQ_MEMBER_CALENDAR_NO.NEXTVAL, '1', '자격증 시험', '2023-08-01','2023-08-03', 'N');
INSERT INTO MEMBER_CALENDAR (NO,WRITER_NO,NAME,START_DATE,END_DATE,LOVE) VALUES (SEQ_MEMBER_CALENDAR_NO.NEXTVAL, '1', '월급', '2023-07-10','2023-07-10', 'N');
INSERT INTO MEMBER_CALENDAR (NO,WRITER_NO,NAME,START_DATE,END_DATE,LOVE) VALUES (SEQ_MEMBER_CALENDAR_NO.NEXTVAL, '1', '대학 동기 결혼식', '2023-07-09','2023-07-15', 'N');
INSERT INTO MEMBER_CALENDAR (NO,WRITER_NO,NAME,START_DATE,END_DATE,LOVE) VALUES (SEQ_MEMBER_CALENDAR_NO.NEXTVAL, '1', '종로 전시회', '2023-08-12','2023-08-12', 'N');
INSERT INTO MEMBER_CALENDAR (NO,WRITER_NO,NAME,START_DATE,END_DATE,LOVE) VALUES (SEQ_MEMBER_CALENDAR_NO.NEXTVAL, '1', '결혼기념일', '2023-08-10','2023-08-10', 'N');


-- 공지 캘린더
INSERT INTO NOTICE_CALENDAR (NO,WRTIER_NO,NAME,START_DATE,END_DATE) VALUES (SEQ_NOTICE_CALENDAR_NO.NEXTVAL, '1', '도서관 시설 공사', '2023-06-29', '2023-06-30');
INSERT INTO NOTICE_CALENDAR (NO,WRTIER_NO,NAME,START_DATE,END_DATE) VALUES (SEQ_NOTICE_CALENDAR_NO.NEXTVAL, '1', '정기 소독일', '2023-07-03', '2023-07-05');
INSERT INTO NOTICE_CALENDAR (NO,WRTIER_NO,NAME,START_DATE,END_DATE) VALUES (SEQ_NOTICE_CALENDAR_NO.NEXTVAL, '1', '외벽 물청소', '2023-07-01', '2023-07-03');
INSERT INTO NOTICE_CALENDAR (NO,WRTIER_NO,NAME,START_DATE,END_DATE) VALUES (SEQ_NOTICE_CALENDAR_NO.NEXTVAL, '1', '승강기 점검', '2023-07-06', '2023-07-10');
INSERT INTO NOTICE_CALENDAR (NO,WRTIER_NO,NAME,START_DATE,END_DATE) VALUES (SEQ_NOTICE_CALENDAR_NO.NEXTVAL, '1', '외벽 도장', '2023-07-15', '2023-07-20');


-- 편의시설
-- 도서관
INSERT INTO AMENITY(NO,NAME,CONTENT,MAX_NUM,LOCATION,OPEN_TIME,CLOSE_TIME) VALUES (SEQ_AMENITY_NO.NEXTVAL, '도서관', '안녕하세요 꿀단지 도서관입니다. 
저희 도서관은 남녀노소 모두에게 열려있는 도서관입니다. 
도서관 관리인 연락처 : 02-4321-9320
*취소는 반드시 하루 전 날에 가능합니다. 
이용하시는데 착오 없으시길 바랍니다.', '3', '1단지 앞 커뮤니티 건물 1층','07:00','23:00');

-- 수영장
INSERT INTO AMENITY(NO,NAME,CONTENT,MAX_NUM,LOCATION,OPEN_TIME,CLOSE_TIME) VALUES (SEQ_AMENITY_NO.NEXTVAL, '수영장', '안녕하세요 꿀단지 수영장입니다. 
수영장 관리인 연락처 : 02-4321-9321
*취소는 반드시 하루 전 날에 가능합니다. 
이용하시는데 착오 없으시길 바랍니다.', '5', '2단지 앞 커뮤니티 건물 지하1층','08:00','22:00');

-- 헬스장
INSERT INTO AMENITY(NO,NAME,CONTENT,MAX_NUM,LOCATION,OPEN_TIME, CLOSE_TIME) VALUES (SEQ_AMENITY_NO.NEXTVAL, '헬스장', '안녕하세요 꿀단지 헬스장입니다. 
헬스장 관리인 연락처 : 02-4321-9322
*취소는 반드시 하루 전 날에 가능합니다. 
이용하시는데 착오 없으시길 바랍니다.', '10', '1단지 앞 커뮤니티 건물 3층','10:00','23:00');

-- 골프장
INSERT INTO AMENITY(NO,NAME,CONTENT,MAX_NUM,LOCATION,OPEN_TIME,CLOSE_TIME) VALUES (SEQ_AMENITY_NO.NEXTVAL, '골프장', '안녕하세요 꿀단지 골프장입니다. 
골프장 관리인 연락처 : 02-4321-9323
*취소는 반드시 하루 전 날에 가능합니다. 
이용하시는데 착오 없으시길 바랍니다.', '4', '3단지 커뮤니티 건물 앞', '12:00','20:00');


-- 편의시설 이미지
INSERT INTO AMENITY_IMG (NO,AMENITY_NO,ORIGIN_NAME) VALUES (SEQ_AMENITY_NO.NEXTVAL, '1', '도서관1.jpg');
INSERT INTO AMENITY_IMG (NO,AMENITY_NO,ORIGIN_NAME) VALUES (SEQ_AMENITY_NO.NEXTVAL, '1', '도서관2.jpg');
INSERT INTO AMENITY_IMG (NO,AMENITY_NO,ORIGIN_NAME) VALUES (SEQ_AMENITY_NO.NEXTVAL, '1', '도서관3.jpg');
INSERT INTO AMENITY_IMG (NO,AMENITY_NO,ORIGIN_NAME) VALUES (SEQ_AMENITY_NO.NEXTVAL, '1', '도서관4.jpg');
INSERT INTO AMENITY_IMG (NO,AMENITY_NO,ORIGIN_NAME) VALUES (SEQ_AMENITY_NO.NEXTVAL, '2', '수영장1.jpg');
INSERT INTO AMENITY_IMG (NO,AMENITY_NO,ORIGIN_NAME) VALUES (SEQ_AMENITY_NO.NEXTVAL, '2', '수영장2.jpg');
INSERT INTO AMENITY_IMG (NO,AMENITY_NO,ORIGIN_NAME) VALUES (SEQ_AMENITY_NO.NEXTVAL, '2', '수영장3.jpg');
INSERT INTO AMENITY_IMG (NO,AMENITY_NO,ORIGIN_NAME) VALUES (SEQ_AMENITY_NO.NEXTVAL, '3', '헬스장1.jpg');
INSERT INTO AMENITY_IMG (NO,AMENITY_NO,ORIGIN_NAME) VALUES (SEQ_AMENITY_NO.NEXTVAL, '3', '헬스장2.jpg');
INSERT INTO AMENITY_IMG (NO,AMENITY_NO,ORIGIN_NAME) VALUES (SEQ_AMENITY_NO.NEXTVAL, '3', '헬스장3.jpg');
INSERT INTO AMENITY_IMG (NO,AMENITY_NO,ORIGIN_NAME) VALUES (SEQ_AMENITY_NO.NEXTVAL, '4', '골프장1.jpg');
INSERT INTO AMENITY_IMG (NO,AMENITY_NO,ORIGIN_NAME) VALUES (SEQ_AMENITY_NO.NEXTVAL, '4', '골프장2.jpg');
INSERT INTO AMENITY_IMG (NO,AMENITY_NO,ORIGIN_NAME) VALUES (SEQ_AMENITY_NO.NEXTVAL, '4', '골프장3.jpg');

-- 편의시설 예약
INSERT INTO AMENITY_RESERVATION (NO,AMENITY_NO,MEMBER_NO,RESERVE_TIME) VALUES (SEQ_AMENITY_RESERVATION_NO.NEXTVAL, '1', '1', '2023-08-15 10');
INSERT INTO AMENITY_RESERVATION (NO,AMENITY_NO,MEMBER_NO,RESERVE_TIME) VALUES (SEQ_AMENITY_RESERVATION_NO.NEXTVAL, '1', '1', '2023-08-16 10');
INSERT INTO AMENITY_RESERVATION (NO,AMENITY_NO,MEMBER_NO,RESERVE_TIME) VALUES (SEQ_AMENITY_RESERVATION_NO.NEXTVAL, '1', '1', '2023-08-17 10');
INSERT INTO AMENITY_RESERVATION (NO,AMENITY_NO,MEMBER_NO,RESERVE_TIME) VALUES (SEQ_AMENITY_RESERVATION_NO.NEXTVAL, '1', '1', '2023-08-18 10');
INSERT INTO AMENITY_RESERVATION (NO,AMENITY_NO,MEMBER_NO,RESERVE_TIME) VALUES (SEQ_AMENITY_RESERVATION_NO.NEXTVAL, '1', '1', '2023-08-22 10');
INSERT INTO AMENITY_RESERVATION (NO,AMENITY_NO,MEMBER_NO,RESERVE_TIME) VALUES (SEQ_AMENITY_RESERVATION_NO.NEXTVAL, '2', '1', '2023-08-25 10');
INSERT INTO AMENITY_RESERVATION (NO,AMENITY_NO,MEMBER_NO,RESERVE_TIME) VALUES (SEQ_AMENITY_RESERVATION_NO.NEXTVAL, '2', '1', '2023-08-28 10');
INSERT INTO AMENITY_RESERVATION (NO,AMENITY_NO,MEMBER_NO,RESERVE_TIME) VALUES (SEQ_AMENITY_RESERVATION_NO.NEXTVAL, '2', '1', '2023-08-15 10');
INSERT INTO AMENITY_RESERVATION (NO,AMENITY_NO,MEMBER_NO,RESERVE_TIME) VALUES (SEQ_AMENITY_RESERVATION_NO.NEXTVAL, '2', '1', '2023-08-10 10');
INSERT INTO AMENITY_RESERVATION (NO,AMENITY_NO,MEMBER_NO,RESERVE_TIME) VALUES (SEQ_AMENITY_RESERVATION_NO.NEXTVAL, '2', '1', '2023-08-18 10');


-- 편의시설 점검
--없어도 될듯하여 삭제~! 더미데이터 넣어주시느라 고생하셨숨다


-- 차량

INSERT INTO CAR (NO,ADMIN_NO,MEMBER_NO,UNIQUE_NUM,IMG,NAME,ENROLL_DATE) 
VALUES (SEQ_MINE_NO.NEXTVAL, '1', '1', '02누2776', 'G80.png', '제네시스 G80, 블랙',TO_DATE('20230815091212','YYYYMMDDHH24MISS'));
INSERT INTO CAR (NO,ADMIN_NO,MEMBER_NO,UNIQUE_NUM,IMG,NAME,ENROLL_DATE ) 
VALUES (SEQ_MINE_NO.NEXTVAL, '1', '1', '08라3839', '산타페.jpg', '싼타페, 화이트',TO_DATE('20230816211230','YYYYMMDDHH24MISS') );
INSERT INTO CAR (NO,ADMIN_NO,MEMBER_NO,UNIQUE_NUM,IMG,NAME,ENROLL_DATE,CONFIRM_DATE) VALUES (SEQ_MINE_NO.NEXTVAL, '1', '2', '23거7887', 'bmw640.jpg', 'bmw 640i, 밝은 브라운',TO_DATE('20230807091212','YYYYMMDDHH24MISS'),TO_DATE('20230808091212','YYYYMMDDHH24MISS') );
INSERT INTO CAR (NO,ADMIN_NO,MEMBER_NO,UNIQUE_NUM,IMG,NAME,ENROLL_DATE,CONFIRM_DATE) VALUES (SEQ_MINE_NO.NEXTVAL, '1', '5', '69너6657', '벤츠.png', '벤츠 s클래스, 블랙',TO_DATE('20230809091212','YYYYMMDDHH24MISS'), TO_DATE('20230810091212','YYYYMMDDHH24MISS') );
INSERT INTO CAR (NO,ADMIN_NO,MEMBER_NO,UNIQUE_NUM,IMG,NAME,ENROLL_DATE,CONFIRM_DATE) VALUES (SEQ_MINE_NO.NEXTVAL, '1', '9', '153호1002', 'G70.png', '제네시스 G70, 블랙',TO_DATE('20230807091612','YYYYMMDDHH24MISS') ,TO_DATE('202308101812','YYYYMMDDHH24MISS') );
INSERT INTO CAR (NO,ADMIN_NO,MEMBER_NO,UNIQUE_NUM,IMG,NAME,ENROLL_DATE,CONFIRM_DATE) VALUES (SEQ_MINE_NO.NEXTVAL, '1', '9', '387누9094', 'A6.png', '아우디 A6, 화이트',TO_DATE('20230807091212','YYYYMMDDHH24MISS') ,TO_DATE('20230807101215','YYYYMMDDHH24MISS') );

-- 바이크 (자전거 + 오토바이)
INSERT INTO BICYCLE (NO,ADMIN_NO,MEMBER_NO,IMG,NAME,UNIQUE_NUM,ENROLL_DATE) 
VALUES (SEQ_MINE_NO.NEXTVAL, '1', '2', '구스타브.jpg', '구스타브28 클래식, 블랙','가00001',TO_DATE('20230814211130','YYYYMMDDHH24MISS'));
INSERT INTO BICYCLE (NO,ADMIN_NO,MEMBER_NO,IMG,NAME,UNIQUE_NUM,ENROLL_DATE) 
VALUES (SEQ_MINE_NO.NEXTVAL, '1', '2', '첼로xc.jpg', '첼로xc 프로 30 MTB, 블랙','나000005',TO_DATE('20230815211927','YYYYMMDDHH24MISS'));
INSERT INTO BICYCLE (NO,ADMIN_NO,MEMBER_NO,IMG,NAME,UNIQUE_NUM,ENROLL_DATE,CONFIRM_DATE) VALUES (SEQ_MINE_NO.NEXTVAL, '1', '5', '사일레스.jpg', '사일렉스700 메리다 , 빨간색','가000003',TO_DATE('20230805211230','YYYYMMDDHH24MISS'),TO_DATE('20230810221130','YYYYMMDDHH24MISS'));
INSERT INTO BICYCLE (NO,ADMIN_NO,MEMBER_NO,IMG,NAME,UNIQUE_NUM,ENROLL_DATE,CONFIRM_DATE) VALUES (SEQ_MINE_NO.NEXTVAL, '1', '7', '트랙마린.jpg', '트렉 마린7 MTB, 노란색','나000004',TO_DATE('20230810211227','YYYYMMDDHH24MISS'),TO_DATE('20230810211230','YYYYMMDDHH24MISS'));
INSERT INTO BICYCLE (NO,ADMIN_NO,MEMBER_NO,IMG,NAME,UNIQUE_NUM,ENROLL_DATE,CONFIRM_DATE) VALUES (SEQ_MINE_NO.NEXTVAL, '1', '7', '알톤16.jpg', '베네톤 알톤 16인치, 분홍색 ','다000092',TO_DATE('20230810181219','YYYYMMDDHH24MISS'),TO_DATE('20230810181529','YYYYMMDDHH24MISS'));
INSERT INTO BICYCLE (NO,ADMIN_NO,MEMBER_NO,IMG,NAME,UNIQUE_NUM,ENROLL_DATE,CONFIRM_DATE) VALUES (SEQ_MINE_NO.NEXTVAL, '1', '9', '야마하yzf.jpg', '야마하 YZF-R3 18년식, 블랙','가000028',TO_DATE('20230811211211','YYYYMMDDHH24MISS'),TO_DATE('20230813191320','YYYYMMDDHH24MISS'));
INSERT INTO BICYCLE (NO,ADMIN_NO,MEMBER_NO,IMG,NAME,UNIQUE_NUM,ENROLL_DATE,CONFIRM_DATE) VALUES (SEQ_MINE_NO.NEXTVAL, '1', '8', '구스타브.jpg', '구스타브28 클래식 블랙','나0000101',TO_DATE('20230810211213','YYYYMMDDHH24MISS'),TO_DATE('20230810211741','YYYYMMDDHH24MISS'));


-- 관리자 호출
INSERT INTO ADMIN_CALL (NO,ADMIN_NO,MEMBER_NO,CONTENT) VALUES (SEQ_ADMIN_CALL_NO.NEXTVAL, '2', '1', '욕실 위 층에서 물이 새는 것 같아요');
INSERT INTO ADMIN_CALL (NO,ADMIN_NO,MEMBER_NO,CONTENT) VALUES (SEQ_ADMIN_CALL_NO.NEXTVAL, '2', '2', '층간 소음이 좀 심하네요');
INSERT INTO ADMIN_CALL (NO,ADMIN_NO,MEMBER_NO,CONTENT) VALUES (SEQ_ADMIN_CALL_NO.NEXTVAL, '3', '5', '싱크대 수도 배관이 터졌어요 ㅜㅜ ');
INSERT INTO ADMIN_CALL (NO,ADMIN_NO,MEMBER_NO,CONTENT) VALUES (SEQ_ADMIN_CALL_NO.NEXTVAL, '3', '5', '욕실 수도에서 녹물이 나와요');
INSERT INTO ADMIN_CALL (NO,ADMIN_NO,MEMBER_NO,CONTENT) VALUES (SEQ_ADMIN_CALL_NO.NEXTVAL, '4', '9', '배달음식이 잘못 온 것 같아요');
INSERT INTO ADMIN_CALL (NO,ADMIN_NO,MEMBER_NO,CONTENT) VALUES (SEQ_ADMIN_CALL_NO.NEXTVAL, '4', '9', '택배 다시 반품하고싶어요');
INSERT INTO ADMIN_CALL (NO,ADMIN_NO,MEMBER_NO,CONTENT) VALUES (SEQ_ADMIN_CALL_NO.NEXTVAL, '6', '11', '관리비 관련해서 급하게 확인하고 싶은 게 있어요');


-- 택배
INSERT INTO PARCEL(NO,MEMBER_NO,ADMIN_NO) VALUES (SEQ_PARCEL_NO.NEXTVAL, '2', '2');
INSERT INTO PARCEL(NO,MEMBER_NO,ADMIN_NO) VALUES (SEQ_PARCEL_NO.NEXTVAL, '5', '3');
INSERT INTO PARCEL(NO,MEMBER_NO,ADMIN_NO) VALUES (SEQ_PARCEL_NO.NEXTVAL, '6', '3');
INSERT INTO PARCEL(NO,MEMBER_NO,ADMIN_NO) VALUES (SEQ_PARCEL_NO.NEXTVAL, '9', '4');
INSERT INTO PARCEL(NO,MEMBER_NO,ADMIN_NO) VALUES (SEQ_PARCEL_NO.NEXTVAL, '11', '6');
INSERT INTO PARCEL(NO,MEMBER_NO,ADMIN_NO) VALUES (SEQ_PARCEL_NO.NEXTVAL, '12', '10');


-- 배달
INSERT INTO DELIVERY (NO,MEMBER_NO,ADMIN_NO) VALUES (SEQ_DELIVERY_NO.NEXTVAL, '1', '2');
INSERT INTO DELIVERY (NO,MEMBER_NO,ADMIN_NO) VALUES (SEQ_DELIVERY_NO.NEXTVAL, '5', '3');
INSERT INTO DELIVERY (NO,MEMBER_NO,ADMIN_NO) VALUES (SEQ_DELIVERY_NO.NEXTVAL, '6', '3');
INSERT INTO DELIVERY (NO,MEMBER_NO,ADMIN_NO) VALUES (SEQ_DELIVERY_NO.NEXTVAL, '9', '4');
INSERT INTO DELIVERY (NO,MEMBER_NO,ADMIN_NO) VALUES (SEQ_DELIVERY_NO.NEXTVAL, '11', '6');


-- 신고 카테고리
INSERT INTO REPORT_CATEGORY (NO, NAME) VALUES (SEQ_REPORT_CATEGORY_NO.NEXTVAL, '욕설/비하/혐오');
INSERT INTO REPORT_CATEGORY (NO, NAME) VALUES (SEQ_REPORT_CATEGORY_NO.NEXTVAL, '부적절한 홍보');
INSERT INTO REPORT_CATEGORY (NO, NAME) VALUES (SEQ_REPORT_CATEGORY_NO.NEXTVAL, '음란물/청소년 유해');
INSERT INTO REPORT_CATEGORY (NO, NAME) VALUES (SEQ_REPORT_CATEGORY_NO.NEXTVAL, '불법성');
INSERT INTO REPORT_CATEGORY (NO, NAME) VALUES (SEQ_REPORT_CATEGORY_NO.NEXTVAL, '사칭/사기');
INSERT INTO REPORT_CATEGORY (NO, NAME) VALUES (SEQ_REPORT_CATEGORY_NO.NEXTVAL, '기타');


-- 신고 내역
INSERT INTO REPORT (NO,REPORT_CNO,REPORTER,RESPONDENT,TITLE,CONTENT) VALUES (SEQ_REPORT_NO.NEXTVAL, '2', '2', '5', '과일가게 홍보가 의심됩니다.', '게시판에서 주기적으로 과일가게 홍보의심글이 있어 신고요청드립니다.');
INSERT INTO REPORT (NO,REPORT_CNO,REPORTER,RESPONDENT,TITLE,CONTENT) VALUES (SEQ_REPORT_NO.NEXTVAL, '1', '3', '6', '욕설 사용', '댓글로 욕했어요');
INSERT INTO REPORT (NO,REPORT_CNO,REPORTER,RESPONDENT,TITLE,CONTENT) VALUES (SEQ_REPORT_NO.NEXTVAL, '6', '1', '8', '유언비어를 퍼뜨리고 다닙니다.', '아파트에 대해 안좋은 얘기를 너무 많이 하네요');
INSERT INTO REPORT (NO,REPORT_CNO,REPORTER,RESPONDENT,TITLE,CONTENT) VALUES (SEQ_REPORT_NO.NEXTVAL, '1', '2', '5', '욕설', '홍보 아니냐고 물었는데 욕했어요');
INSERT INTO REPORT (NO,REPORT_CNO,REPORTER,RESPONDENT,TITLE,CONTENT) VALUES (SEQ_REPORT_NO.NEXTVAL, '4', '6', '10', '장터에서 팔면 안되는 거 팜', '흠뻑쇼 플미 붙여서 팔았어요.');
INSERT INTO REPORT (NO,REPORT_CNO,REPORTER,RESPONDENT,TITLE,CONTENT) VALUES (SEQ_REPORT_NO.NEXTVAL, '4', '5', '10', '상품 가격을 말도 안되게 파네요', '먹태깡 원가의 10배로 팔아요. 불법 아닌가요?');
INSERT INTO REPORT (NO,REPORT_CNO,REPORTER,RESPONDENT,TITLE,CONTENT) VALUES (SEQ_REPORT_NO.NEXTVAL, '3', '4', '8', '댓글로 이상한 거 올려요', '확인해주세요');


-- 제재
INSERT INTO RESTRICTION (NO,ADMIN_NO,MEMBER_NO,CONTENT,STOP_NUM) VALUES (SEQ_RESTRICTION_NO.NEXTVAL, '1', '5', '잦은 홍보 신고로 인한 제재', '2');
INSERT INTO RESTRICTION (NO,ADMIN_NO,MEMBER_NO,CONTENT,STOP_NUM) VALUES (SEQ_RESTRICTION_NO.NEXTVAL, '1', '6', '심한 욕설 사용', '5');
INSERT INTO RESTRICTION (NO,ADMIN_NO,MEMBER_NO,CONTENT,STOP_NUM) VALUES (SEQ_RESTRICTION_NO.NEXTVAL, '1', '8', '누적 신고 수가 많음', '1');


-- 상벌점
INSERT INTO POINT (NO,MEMBER_NO,ADMIN_NO,SCORE,CONTENT) VALUES(SEQ_POINT_NO.NEXTVAL, '1', '1', '5', '쓰레기 줍기');
INSERT INTO POINT (NO,MEMBER_NO,ADMIN_NO,SCORE,CONTENT) VALUES(SEQ_POINT_NO.NEXTVAL, '1', '1', '-5', '쓰레기 투기');
INSERT INTO POINT (NO,MEMBER_NO,ADMIN_NO,SCORE,CONTENT) VALUES(SEQ_POINT_NO.NEXTVAL, '1', '1', '-30', '주민 폭행');
INSERT INTO POINT (NO,MEMBER_NO,ADMIN_NO,SCORE,CONTENT) VALUES(SEQ_POINT_NO.NEXTVAL, '1', '1', '-20', '반려동물 배설물 미처리');
INSERT INTO POINT (NO,MEMBER_NO,ADMIN_NO,SCORE,CONTENT) VALUES(SEQ_POINT_NO.NEXTVAL, '1', '1', '-30', '층간소음');
INSERT INTO POINT (NO,MEMBER_NO,ADMIN_NO,SCORE,CONTENT) VALUES(SEQ_POINT_NO.NEXTVAL, '1', '1', '10', '아이 돌보기');
INSERT INTO POINT (NO,MEMBER_NO,ADMIN_NO,SCORE,CONTENT) VALUES(SEQ_POINT_NO.NEXTVAL, '1', '1', '-5', '주민 신고');


-- 채팅방
INSERT INTO CHATTING_ROOM (NO,MASTER_NO,NAME,IMG) VALUES (SEQ_CHATTING_ROOM_NO.NEXTVAL, '1', '101동 골프모임', 'golf.jpg');
INSERT INTO CHATTING_ROOM (NO,MASTER_NO,NAME,IMG) VALUES (SEQ_CHATTING_ROOM_NO.NEXTVAL, '5', '101동 골프모임', 'golf.jpg');


-- 채팅 멤버 리스트
INSERT INTO CHATTING_MEMBER_LIST (CHATTING_ROOM_NO,MEMBER_NO,READ_TIME) VALUES ('1', '1', '2023-07-10 13:28:00');
INSERT INTO CHATTING_MEMBER_LIST (CHATTING_ROOM_NO,MEMBER_NO,READ_TIME) VALUES ('1', '2', '2023-07-10 13:10:28');
INSERT INTO CHATTING_MEMBER_LIST (CHATTING_ROOM_NO,MEMBER_NO,READ_TIME) VALUES ('1', '13', '2023-07-10 13:33:24');
INSERT INTO CHATTING_MEMBER_LIST (CHATTING_ROOM_NO,MEMBER_NO,READ_TIME) VALUES ('1', '14', '2023-07-10 13:35:33');
INSERT INTO CHATTING_MEMBER_LIST (CHATTING_ROOM_NO,MEMBER_NO,READ_TIME) VALUES ('1', '15', '2023-07-10 13:36:11');
INSERT INTO CHATTING_MEMBER_LIST (CHATTING_ROOM_NO,MEMBER_NO,READ_TIME) VALUES ('2', '5', '2023-07-10 15:33:20');
INSERT INTO CHATTING_MEMBER_LIST (CHATTING_ROOM_NO,MEMBER_NO,READ_TIME) VALUES ('2', '9', '2023-07-10 15:37:55');


-- 채팅 메세지
INSERT INTO CHATTING_MESSAGE(NO,CHATTING_ROOM_NO,MEMBER_NO, CONTENT, SEND_TIME) VALUES (SEQ_CHATTING_MESSAGE_NO.NEXTVAL, '1', '13' , '어제 금액 정산합시다.', '2023-08-01 10:15:03' );
INSERT INTO CHATTING_MESSAGE(NO,CHATTING_ROOM_NO,MEMBER_NO, CONTENT, SEND_TIME) VALUES (SEQ_CHATTING_MESSAGE_NO.NEXTVAL, '1', '14', '네~ ', '2023-08-01 10:16:03');
INSERT INTO CHATTING_MESSAGE(NO,CHATTING_ROOM_NO,MEMBER_NO, CONTENT, SEND_TIME) VALUES (SEQ_CHATTING_MESSAGE_NO.NEXTVAL, '1', '14', '총무님~ ', '2023-08-01 10:18:03');
INSERT INTO CHATTING_MESSAGE(NO,CHATTING_ROOM_NO,MEMBER_NO, CONTENT, SEND_TIME) VALUES (SEQ_CHATTING_MESSAGE_NO.NEXTVAL, '1', '15', '잠시만요. 정산하고 말씀드릴게요', '2023-08-01 10:20:03');
INSERT INTO CHATTING_MESSAGE(NO,CHATTING_ROOM_NO,MEMBER_NO, CONTENT, SEND_TIME) VALUES (SEQ_CHATTING_MESSAGE_NO.NEXTVAL, '2', '5', '내일 등산 가는 거 어떰', '2023-08-01 10:15:03');
INSERT INTO CHATTING_MESSAGE(NO,CHATTING_ROOM_NO,MEMBER_NO, CONTENT, SEND_TIME) VALUES (SEQ_CHATTING_MESSAGE_NO.NEXTVAL, '2', '1','ㅇㅋㅇㅋ 좋음. 어디로?', '2023-08-01 10:16:03');
INSERT INTO CHATTING_MESSAGE(NO,CHATTING_ROOM_NO,MEMBER_NO, CONTENT, SEND_TIME) VALUES (SEQ_CHATTING_MESSAGE_NO.NEXTVAL, '2', '5','관악산?', '2023-08-01 10:17:03');
INSERT INTO CHATTING_MESSAGE(NO,CHATTING_ROOM_NO,MEMBER_NO, CONTENT, SEND_TIME) VALUES (SEQ_CHATTING_MESSAGE_NO.NEXTVAL, '2', '1','ㄴㄴ 청계산 가자', '2023-08-01 10:18:03');
INSERT INTO CHATTING_MESSAGE(NO,CHATTING_ROOM_NO,MEMBER_NO, CONTENT, SEND_TIME) VALUES (SEQ_CHATTING_MESSAGE_NO.NEXTVAL, '2', '5','몇 시까지 만날까', '2023-08-01 10:19:03');
INSERT INTO CHATTING_MESSAGE(NO,CHATTING_ROOM_NO,MEMBER_NO, CONTENT, SEND_TIME) VALUES (SEQ_CHATTING_MESSAGE_NO.NEXTVAL, '2', '1','8시까지 정문에서 만나', '2023-08-01 10:20:03');

-- 동대표 호감도
INSERT INTO CAPTAIN_LOVE (MEMBER_NO,CAPTAIN_NO,LOVE) VALUES ('11', '11', 'L');
INSERT INTO CAPTAIN_LOVE (MEMBER_NO,CAPTAIN_NO,LOVE) VALUES ('12', '12', 'L');
INSERT INTO CAPTAIN_LOVE (MEMBER_NO,CAPTAIN_NO,LOVE) VALUES ('1', '13', 'L');
INSERT INTO CAPTAIN_LOVE (MEMBER_NO,CAPTAIN_NO,LOVE) VALUES ('2', '13', 'L');
INSERT INTO CAPTAIN_LOVE (MEMBER_NO,CAPTAIN_NO,LOVE) VALUES ('3', '13', 'L');
INSERT INTO CAPTAIN_LOVE (MEMBER_NO,CAPTAIN_NO,LOVE) VALUES ('4', '13', 'L');
INSERT INTO CAPTAIN_LOVE (MEMBER_NO,CAPTAIN_NO,LOVE) VALUES ('5', '13', 'H');
INSERT INTO CAPTAIN_LOVE (MEMBER_NO,CAPTAIN_NO,LOVE) VALUES ('6', '13', 'H');
INSERT INTO CAPTAIN_LOVE (MEMBER_NO,CAPTAIN_NO,LOVE) VALUES ('7', '13', 'H');

-- 친구
INSERT INTO FRIEND (NO, MEMBER_NO, FRIEND_NO) VALUES(SEQ_FRIEND_NO.NEXTVAL, '1', '2');
INSERT INTO FRIEND (NO, MEMBER_NO, FRIEND_NO) VALUES(SEQ_FRIEND_NO.NEXTVAL, '1', '3');
INSERT INTO FRIEND (NO, MEMBER_NO, FRIEND_NO) VALUES(SEQ_FRIEND_NO.NEXTVAL, '1', '4');
INSERT INTO FRIEND (NO, MEMBER_NO, FRIEND_NO) VALUES(SEQ_FRIEND_NO.NEXTVAL, '1', '5');
INSERT INTO FRIEND (NO, MEMBER_NO, FRIEND_NO) VALUES(SEQ_FRIEND_NO.NEXTVAL, '1', '6');
INSERT INTO FRIEND (NO, MEMBER_NO, FRIEND_NO) VALUES(SEQ_FRIEND_NO.NEXTVAL, '1', '7');
INSERT INTO FRIEND (NO, MEMBER_NO, FRIEND_NO) VALUES(SEQ_FRIEND_NO.NEXTVAL, '1', '8');
INSERT INTO FRIEND (NO, MEMBER_NO, FRIEND_NO) VALUES(SEQ_FRIEND_NO.NEXTVAL, '1', '9');
INSERT INTO FRIEND (NO, MEMBER_NO, FRIEND_NO) VALUES(SEQ_FRIEND_NO.NEXTVAL, '1', '10');
INSERT INTO FRIEND (NO, MEMBER_NO, FRIEND_NO) VALUES(SEQ_FRIEND_NO.NEXTVAL, '1', '11');


-- 비품
INSERT INTO EQUIPMENT (NO, ADMIN_NO, NAME, CNT) VALUES(SEQ_EQUIPMENT_NO.NEXTVAL, '1', '빗자루', '100');
INSERT INTO EQUIPMENT (NO, ADMIN_NO, NAME, CNT) VALUES(SEQ_EQUIPMENT_NO.NEXTVAL, '1', '쓰레받기', '100');
INSERT INTO EQUIPMENT (NO, ADMIN_NO, NAME, CNT) VALUES(SEQ_EQUIPMENT_NO.NEXTVAL, '1', '합판', '50');
INSERT INTO EQUIPMENT (NO, ADMIN_NO, NAME, CNT) VALUES(SEQ_EQUIPMENT_NO.NEXTVAL, '1', '쇠파이프', '30');
INSERT INTO EQUIPMENT (NO, ADMIN_NO, NAME, CNT) VALUES(SEQ_EQUIPMENT_NO.NEXTVAL, '1', '경광봉', '150');
INSERT INTO EQUIPMENT (NO, ADMIN_NO, NAME, CNT) VALUES(SEQ_EQUIPMENT_NO.NEXTVAL, '1', '시멘트(1L)', '200');


-- FAQ 카테고리
INSERT INTO FAQ_CATEGORY(NO, NAME) VALUES(SEQ_FAQ_CATEGORY_NO.NEXTVAL, '회원정보');
INSERT INTO FAQ_CATEGORY(NO, NAME) VALUES(SEQ_FAQ_CATEGORY_NO.NEXTVAL, '결제');
INSERT INTO FAQ_CATEGORY(NO, NAME) VALUES(SEQ_FAQ_CATEGORY_NO.NEXTVAL, '편의시설');
INSERT INTO FAQ_CATEGORY(NO, NAME) VALUES(SEQ_FAQ_CATEGORY_NO.NEXTVAL, '기타');


-- FAQ
INSERT INTO FAQ(NO, WRITER_NO, FAQ_CNO, QUESTION, ANSWER, HIT) VALUES(SEQ_FAQ_NO.NEXTVAL, '1', '1', '회원가입은 어떻게 하나요?', '회원가입은 
아파트 주민인 경우 회원가입 요청을 하면 관리자가 승인해주는 형태로 이루어지고 있습니다.
아파트 주민인 경우 일반적인 회원가입이 가능한 상태로 실명인증 동의 절차를 거치신후 회원가입을 하시면 됩니다', '200');
INSERT INTO FAQ(NO, WRITER_NO, FAQ_CNO, QUESTION, ANSWER, HIT) VALUES(SEQ_FAQ_NO.NEXTVAL, '1', '1', '여러 개의 아이디를 하나로 통합할 수 있나요?', '푸리미엄 꿀단지 그룹웨어에서는 아이디 통합 서비스를 제공하지 않습니다.', '250');
INSERT INTO FAQ(NO, WRITER_NO, FAQ_CNO, QUESTION, ANSWER, HIT) VALUES(SEQ_FAQ_NO.NEXTVAL, '1', '1', '아이디를 변경하고싶어요.', '현재 사용중인 아이디는 변경하실 수 없습니다.
다만, 새로운 아이디를 만들어 사용하실 수 있습니다.
관리자에게 문의를 남겨주세요.', '180');
INSERT INTO FAQ(NO, WRITER_NO, FAQ_CNO, QUESTION, ANSWER, HIT) VALUES(SEQ_FAQ_NO.NEXTVAL, '1', '1', '개인정보 변경을 하고싶어요.', '개인정보를 변경하시려면 프로필의 톱니바퀴 버튼을 눌러주세요.', '302');


-- 문의 카테고리
INSERT INTO QNA_CATEGORY(NO, NAME) VALUES(SEQ_QNA_CATEGORY_NO.NEXTVAL, '일반 문의');
INSERT INTO QNA_CATEGORY(NO, NAME) VALUES(SEQ_QNA_CATEGORY_NO.NEXTVAL, '신고');
INSERT INTO QNA_CATEGORY(NO, NAME) VALUES(SEQ_QNA_CATEGORY_NO.NEXTVAL, '건의');
INSERT INTO QNA_CATEGORY(NO, NAME) VALUES(SEQ_QNA_CATEGORY_NO.NEXTVAL, '기타');


-- 문의 내역
INSERT INTO QNA(NO, QNA_CNO, MEMBER_NO, TITLE, CONTENT) VALUES(SEQ_QNA_NO.NEXTVAL, 1, 1, '회원가입 어떻게 해요?', '회원가입을 어디서 하는 지 못 찾겠어요 ㅠㅠ');
INSERT INTO QNA(NO, QNA_CNO, MEMBER_NO, TITLE, CONTENT) VALUES(SEQ_QNA_NO.NEXTVAL, 1, 1, '로그인이 안돼요', '어제까지는 잘 됐는데 오늘부터 안돼요');
INSERT INTO QNA(NO, QNA_CNO, MEMBER_NO, TITLE, CONTENT) VALUES(SEQ_QNA_NO.NEXTVAL, 3, 1, '헬스장 건의', '런닝머신도 추가해주세요');
INSERT INTO QNA(NO, QNA_CNO, MEMBER_NO, TITLE, CONTENT) VALUES(SEQ_QNA_NO.NEXTVAL, 2, 1, '층간소음 신고', '103동 501호 쿵쿵거리는게 너무 심한데 주의 좀 주시기 바랍니다');


-- 회원 관리비 카테고리
INSERT INTO MEMBER_FEE_CATEGORY VALUES(SEQ_MEMBER_FEE_CATEGORY_NO.NEXTVAL, '일반관리비');
INSERT INTO MEMBER_FEE_CATEGORY VALUES(SEQ_MEMBER_FEE_CATEGORY_NO.NEXTVAL, '경비비');
INSERT INTO MEMBER_FEE_CATEGORY VALUES(SEQ_MEMBER_FEE_CATEGORY_NO.NEXTVAL, '청소비');
INSERT INTO MEMBER_FEE_CATEGORY VALUES(SEQ_MEMBER_FEE_CATEGORY_NO.NEXTVAL, '수도 및 온수비');
INSERT INTO MEMBER_FEE_CATEGORY VALUES(SEQ_MEMBER_FEE_CATEGORY_NO.NEXTVAL, '전기료');
INSERT INTO MEMBER_FEE_CATEGORY VALUES(SEQ_MEMBER_FEE_CATEGORY_NO.NEXTVAL, '난방비');
INSERT INTO MEMBER_FEE_CATEGORY VALUES(SEQ_MEMBER_FEE_CATEGORY_NO.NEXTVAL, '수선유지비');
INSERT INTO MEMBER_FEE_CATEGORY VALUES(SEQ_MEMBER_FEE_CATEGORY_NO.NEXTVAL, '관리사무비');
INSERT INTO MEMBER_FEE_CATEGORY VALUES(SEQ_MEMBER_FEE_CATEGORY_NO.NEXTVAL, '정화조비');
INSERT INTO MEMBER_FEE_CATEGORY VALUES(SEQ_MEMBER_FEE_CATEGORY_NO.NEXTVAL, '공동설비유지비');
INSERT INTO MEMBER_FEE_CATEGORY VALUES(SEQ_MEMBER_FEE_CATEGORY_NO.NEXTVAL, '공동주택 관리비');
INSERT INTO MEMBER_FEE_CATEGORY VALUES(SEQ_MEMBER_FEE_CATEGORY_NO.NEXTVAL, '기타');


-- 회원 관리비 내역
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '1', '50000', '2023-07-25');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '2', '20000', '2023-07-25');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '3', '30000', '2023-07-25');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '4', '70000', '2023-07-25');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '5', '90000', '2023-07-25');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '6', '50000', '2023-07-25');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '7', '10000', '2023-07-25');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '8', '10000', '2023-07-25');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '9', '10000', '2023-07-25');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '10', '10000', '2023-07-25');

INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE,STATUS) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '1', '50000', '2023-06-24','Y');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE,STATUS) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '2', '25000', '2023-06-24','Y');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE,STATUS) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '3', '30600', '2023-06-24','Y');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE,STATUS) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '4', '62000', '2023-06-24','Y');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE,STATUS) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '5', '90000', '2023-06-24','Y');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE,STATUS) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '6', '50000', '2023-06-24','Y');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE,STATUS) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '7', '8000', '2023-06-24','Y');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE,STATUS) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '8', '22000', '2023-06-24','Y');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE,STATUS) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '9', '10000', '2023-06-24','Y');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE,STATUS) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '10', '3000', '2023-06-24','Y');

INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE,STATUS) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '1', '40000', '2022-07-18','Y');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE,STATUS) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '2', '20000', '2022-07-18','Y');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE,STATUS) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '3', '15000', '2022-07-18','Y');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE,STATUS) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '4', '70000', '2022-07-18','Y');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE,STATUS) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '5', '80000', '2022-07-18','Y');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE,STATUS) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '6', '50000', '2022-07-18','Y');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE,STATUS) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '7', '10000', '2022-07-18','Y');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE,STATUS) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '8', '10000', '2022-07-18','Y');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE,STATUS) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '9', '10000', '2022-07-18','Y');
INSERT INTO MEMBER_FEE(NO, MEMBER_NO, FEE_CNO, PRICE, PAYMENT_DATE,STATUS) VALUES(SEQ_MEMBER_FEE_NO.NEXTVAL, '1', '10', '10000', '2022-07-18','Y');


-- 관리자 관리비 카테고리
INSERT INTO ADMIN_FEE_CATEGORY VALUES(SEQ_ADMIN_FEE_CATEGORY_NO.NEXTVAL, '시설 유지보수');
INSERT INTO ADMIN_FEE_CATEGORY VALUES(SEQ_ADMIN_FEE_CATEGORY_NO.NEXTVAL, '소독 및 청소');
INSERT INTO ADMIN_FEE_CATEGORY VALUES(SEQ_ADMIN_FEE_CATEGORY_NO.NEXTVAL, '경비원 비용');
INSERT INTO ADMIN_FEE_CATEGORY VALUES(SEQ_ADMIN_FEE_CATEGORY_NO.NEXTVAL, '정원 가꾸기');
INSERT INTO ADMIN_FEE_CATEGORY VALUES(SEQ_ADMIN_FEE_CATEGORY_NO.NEXTVAL, '보험');
INSERT INTO ADMIN_FEE_CATEGORY VALUES(SEQ_ADMIN_FEE_CATEGORY_NO.NEXTVAL, '공공 요금');
INSERT INTO ADMIN_FEE_CATEGORY VALUES(SEQ_ADMIN_FEE_CATEGORY_NO.NEXTVAL, '일반 관리비');
INSERT INTO ADMIN_FEE_CATEGORY VALUES(SEQ_ADMIN_FEE_CATEGORY_NO.NEXTVAL, '기타');


-- 관리자 관리비 내역
INSERT INTO ADMIN_FEE(NO, ADMIN_NO, FEE_CNO, PRICE, PAYMENT_DATE, CONTENT) VALUES(SEQ_ADMIN_FEE_NO.NEXTVAL, '1', '1', '116000', '2023-07-03', '주차장 천장 누수 공사');
INSERT INTO ADMIN_FEE(NO, ADMIN_NO, FEE_CNO, PRICE, PAYMENT_DATE, CONTENT) VALUES(SEQ_ADMIN_FEE_NO.NEXTVAL, '1', '2', '300000', '2023-07-05', '업체 변경');
INSERT INTO ADMIN_FEE(NO, ADMIN_NO, FEE_CNO, PRICE, PAYMENT_DATE, CONTENT) VALUES(SEQ_ADMIN_FEE_NO.NEXTVAL, '1', '3', '27000000', '2023-07-15', '9명');
INSERT INTO ADMIN_FEE(NO, ADMIN_NO, FEE_CNO, PRICE, PAYMENT_DATE) VALUES(SEQ_ADMIN_FEE_NO.NEXTVAL, '1', '4', '70000', '2023-07-17');
INSERT INTO ADMIN_FEE(NO, ADMIN_NO, FEE_CNO, PRICE, PAYMENT_DATE, CONTENT) VALUES(SEQ_ADMIN_FEE_NO.NEXTVAL, '1', '5', '450000' , '2023-07-20', '화재보험료');
INSERT INTO ADMIN_FEE(NO, ADMIN_NO, FEE_CNO, PRICE, PAYMENT_DATE, CONTENT) VALUES(SEQ_ADMIN_FEE_NO.NEXTVAL, '1', '6', '14550000' , '2023-07-25', '열요금');
INSERT INTO ADMIN_FEE(NO, ADMIN_NO, FEE_CNO, PRICE, PAYMENT_DATE, CONTENT) VALUES(SEQ_ADMIN_FEE_NO.NEXTVAL, '1', '6', '118000000' , '2023-07-25', '전기요금');
INSERT INTO ADMIN_FEE(NO, ADMIN_NO, FEE_CNO, PRICE, PAYMENT_DATE, CONTENT) VALUES(SEQ_ADMIN_FEE_NO.NEXTVAL, '1', '6', '8600000' , '2023-07-25', '수도료');
INSERT INTO ADMIN_FEE(NO, ADMIN_NO, FEE_CNO, PRICE, PAYMENT_DATE) VALUES(SEQ_ADMIN_FEE_NO.NEXTVAL, '1', '7', '21000000', '2023-07-30');
INSERT INTO ADMIN_FEE(NO, ADMIN_NO, FEE_CNO, PRICE, PAYMENT_DATE, CONTENT) VALUES(SEQ_ADMIN_FEE_NO.NEXTVAL, '1', '8', '26000000', '2023-07-22', '커뮤니티이용료');

INSERT INTO ADMIN_FEE(NO, ADMIN_NO, FEE_CNO, PRICE, PAYMENT_DATE, CONTENT) VALUES(SEQ_ADMIN_FEE_NO.NEXTVAL, '1', '1', '116000', '2023-06-03', '주차장 천장 누수 공사');
INSERT INTO ADMIN_FEE(NO, ADMIN_NO, FEE_CNO, PRICE, PAYMENT_DATE, CONTENT) VALUES(SEQ_ADMIN_FEE_NO.NEXTVAL, '1', '2', '300000', '2023-06-05', '업체 변경');
INSERT INTO ADMIN_FEE(NO, ADMIN_NO, FEE_CNO, PRICE, PAYMENT_DATE, CONTENT) VALUES(SEQ_ADMIN_FEE_NO.NEXTVAL, '1', '3', '27000000', '2023-06-15', '9명');
INSERT INTO ADMIN_FEE(NO, ADMIN_NO, FEE_CNO, PRICE, PAYMENT_DATE) VALUES(SEQ_ADMIN_FEE_NO.NEXTVAL, '1', '4', '70000', '2023-06-17');
INSERT INTO ADMIN_FEE(NO, ADMIN_NO, FEE_CNO, PRICE, PAYMENT_DATE, CONTENT) VALUES(SEQ_ADMIN_FEE_NO.NEXTVAL, '1', '5', '450000' , '2023-06-20', '화재보험료');
INSERT INTO ADMIN_FEE(NO, ADMIN_NO, FEE_CNO, PRICE, PAYMENT_DATE, CONTENT) VALUES(SEQ_ADMIN_FEE_NO.NEXTVAL, '1', '6', '14550000' , '2023-06-25', '열요금');
INSERT INTO ADMIN_FEE(NO, ADMIN_NO, FEE_CNO, PRICE, PAYMENT_DATE, CONTENT) VALUES(SEQ_ADMIN_FEE_NO.NEXTVAL, '1', '6', '118000000' , '2023-06-25', '전기요금');
INSERT INTO ADMIN_FEE(NO, ADMIN_NO, FEE_CNO, PRICE, PAYMENT_DATE, CONTENT) VALUES(SEQ_ADMIN_FEE_NO.NEXTVAL, '1', '6', '8600000' , '2023-06-25', '수도료');
INSERT INTO ADMIN_FEE(NO, ADMIN_NO, FEE_CNO, PRICE, PAYMENT_DATE) VALUES(SEQ_ADMIN_FEE_NO.NEXTVAL, '1', '7', '21000000', '2023-06-30');
INSERT INTO ADMIN_FEE(NO, ADMIN_NO, FEE_CNO, PRICE, PAYMENT_DATE, CONTENT) VALUES(SEQ_ADMIN_FEE_NO.NEXTVAL, '1', '8', '26000000', '2023-06-22', '커뮤니티이용료');


-- 게시판 카테고리
INSERT INTO BOARD_CATEGORY (NO, NAME) VALUES (1, '자유 게시판');
INSERT INTO BOARD_CATEGORY (NO, NAME) VALUES (2, '장터 게시판');
INSERT INTO BOARD_CATEGORY (NO, NAME) VALUES (3, '익명 게시판');
INSERT INTO BOARD_CATEGORY (NO, NAME) VALUES (4, '칭찬 게시판');

-- 게시글 상태
INSERT INTO BOARD_STATUS (NO, NAME) VALUES (1, '일반');
INSERT INTO BOARD_STATUS (NO, NAME) VALUES (2, '판매');
INSERT INTO BOARD_STATUS (NO, NAME) VALUES (3, '구매');
INSERT INTO BOARD_STATUS (NO, NAME) VALUES (4, '거래완료');
INSERT INTO BOARD_STATUS (NO, NAME) VALUES (5, '삭제');

-- 게시글
--자유
INSERT INTO BOARD (NO,WRITER_NO,BOARD_STATUS_NO,BOARD_CNO,TITLE,CONTENT,HIT) VALUES (SEQ_BOARD_NO.NEXTVAL,1,1,1,'안녕하세요11','반갑습니다~',10);
INSERT INTO BOARD (NO,WRITER_NO,BOARD_STATUS_NO,BOARD_CNO,TITLE,CONTENT,HIT) VALUES (SEQ_BOARD_NO.NEXTVAL,1,1,1,'안녕하세요12','반갑습니다~',9);
INSERT INTO BOARD (NO,WRITER_NO,BOARD_STATUS_NO,BOARD_CNO,TITLE,CONTENT,HIT) VALUES (SEQ_BOARD_NO.NEXTVAL,1,1,1,'안녕하세요13','반갑습니다~',8);
INSERT INTO BOARD (NO,WRITER_NO,BOARD_STATUS_NO,BOARD_CNO,TITLE,CONTENT,HIT) VALUES (SEQ_BOARD_NO.NEXTVAL,1,1,1,'안녕하세요14','반갑습니다~',7);
INSERT INTO BOARD (NO,WRITER_NO,BOARD_STATUS_NO,BOARD_CNO,TITLE,CONTENT,HIT) VALUES (SEQ_BOARD_NO.NEXTVAL,1,1,1,'안녕하세요15','반갑습니다~',6);
INSERT INTO BOARD (NO,WRITER_NO,BOARD_STATUS_NO,BOARD_CNO,TITLE,CONTENT,HIT) VALUES (SEQ_BOARD_NO.NEXTVAL,2,1,1,'안녕하세요21','반갑습니다~',5);
INSERT INTO BOARD (NO,WRITER_NO,BOARD_STATUS_NO,BOARD_CNO,TITLE,CONTENT,HIT) VALUES (SEQ_BOARD_NO.NEXTVAL,2,1,1,'안녕하세요22','반갑습니다~',4);
INSERT INTO BOARD (NO,WRITER_NO,BOARD_STATUS_NO,BOARD_CNO,TITLE,CONTENT,HIT) VALUES (SEQ_BOARD_NO.NEXTVAL,2,1,1,'안녕하세요23','반갑습니다~',3);
INSERT INTO BOARD (NO,WRITER_NO,BOARD_STATUS_NO,BOARD_CNO,TITLE,CONTENT,HIT) VALUES (SEQ_BOARD_NO.NEXTVAL,3,1,1,'안녕하세요31','반갑습니다~',2);
INSERT INTO BOARD (NO,WRITER_NO,BOARD_STATUS_NO,BOARD_CNO,TITLE,CONTENT,HIT) VALUES (SEQ_BOARD_NO.NEXTVAL,3,1,1,'안녕하세요32','반갑습니다~',1);
INSERT INTO BOARD (NO,WRITER_NO,BOARD_STATUS_NO,BOARD_CNO,TITLE,CONTENT,HIT) VALUES (SEQ_BOARD_NO.NEXTVAL,3,1,1,'안녕하세요33','반갑습니다~',11);
--장터
--익명
--칭찬
INSERT INTO BOARD (NO,WRITER_NO,BOARD_STATUS_NO,BOARD_CNO,TITLE,CONTENT) VALUES (SEQ_BOARD_NO.NEXTVAL,1,1,4,'심구용 이웃을 칭찬합니다','자발적으로 단지 미화하는 모습이 아름답습니다.');



-- 공지사항 카테고리
INSERT INTO NOTICE_CATEGORY (NO, NAME) VALUES (1, '일반');
INSERT INTO NOTICE_CATEGORY (NO, NAME) VALUES (2, '시설');
INSERT INTO NOTICE_CATEGORY (NO, NAME) VALUES (3, '관리');
INSERT INTO NOTICE_CATEGORY (NO, NAME) VALUES (4, '행사');


-- 공지사항
-- 일반
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,1,1,'안녕하세요 꿀단지입니다','상호 존중하며 이용해주시길 부탁드립니다 ^^',TO_TIMESTAMP('2023-08-01 12:00', 'YYYY-MM-DD HH24:MI'),10,'N');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,1,1,'안녕하세요 꿀단지입니다','상호 존중하며 이용해주시길 부탁드립니다 ^^',TO_TIMESTAMP('2023-08-01 12:10', 'YYYY-MM-DD HH24:MI'),9,'N');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,1,1,'안녕하세요 꿀단지입니다','상호 존중하며 이용해주시길 부탁드립니다 ^^',TO_TIMESTAMP('2023-08-01 12:20', 'YYYY-MM-DD HH24:MI'),8,'N');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,1,1,'안녕하세요 꿀단지입니다','상호 존중하며 이용해주시길 부탁드립니다 ^^',TO_TIMESTAMP('2023-08-01 12:30', 'YYYY-MM-DD HH24:MI'),7,'N');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,1,1,'안녕하세요 꿀단지입니다','상호 존중하며 이용해주시길 부탁드립니다 ^^',TO_TIMESTAMP('2023-08-01 12:40', 'YYYY-MM-DD HH24:MI'),6,'N');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,1,1,'안녕하세요 꿀단지입니다','상호 존중하며 이용해주시길 부탁드립니다 ^^',TO_TIMESTAMP('2023-08-01 12:50', 'YYYY-MM-DD HH24:MI'),5,'N');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,1,1,'안녕하세요 꿀단지입니다','상호 존중하며 이용해주시길 부탁드립니다 ^^',TO_TIMESTAMP('2023-08-01 13:00', 'YYYY-MM-DD HH24:MI'),4,'N');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,1,1,'안녕하세요 꿀단지입니다','상호 존중하며 이용해주시길 부탁드립니다 ^^',TO_TIMESTAMP('2023-08-01 13:10', 'YYYY-MM-DD HH24:MI'),3,'N');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,1,1,'안녕하세요 꿀단지입니다','상호 존중하며 이용해주시길 부탁드립니다 ^^',TO_TIMESTAMP('2023-08-01 13:20', 'YYYY-MM-DD HH24:MI'),2,'N');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,1,1,'안녕하세요 꿀단지입니다','상호 존중하며 이용해주시길 부탁드립니다 ^^',TO_TIMESTAMP('2023-08-01 13:30', 'YYYY-MM-DD HH24:MI'),1,'N');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,1,1,'101동 대표 선거','주민 여러분의 적극 참여 바랍니다 ^^',TO_TIMESTAMP('2023-08-02 14:00', 'YYYY-MM-DD HH24:MI'),5,'Y');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,1,1,'102동 대표 선거','주민 여러분의 적극 참여 바랍니다 ^^',TO_TIMESTAMP('2023-08-02 14:10', 'YYYY-MM-DD HH24:MI'),6,'Y');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,1,1,'103동 대표 선거','주민 여러분의 적극 참여 바랍니다 ^^',TO_TIMESTAMP('2023-08-02 14:20', 'YYYY-MM-DD HH24:MI'),7,'Y');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,1,1,'101동 대표 선거','주민 여러분의 적극 참여 바랍니다 ^^',TO_TIMESTAMP('2023-08-02 15:00', 'YYYY-MM-DD HH24:MI'),8,'N');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,1,1,'102동 대표 선거','주민 여러분의 적극 참여 바랍니다 ^^',TO_TIMESTAMP('2023-08-02 15:10', 'YYYY-MM-DD HH24:MI'),9,'N');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,1,1,'103동 대표 선거','주민 여러분의 적극 참여 바랍니다 ^^',TO_TIMESTAMP('2023-08-02 15:20', 'YYYY-MM-DD HH24:MI'),10,'N');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,1,1,'101동 대표 선거','주민 여러분의 적극 참여 바랍니다 ^^',TO_TIMESTAMP('2023-08-02 16:00', 'YYYY-MM-DD HH24:MI'),11,'N');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,1,1,'102동 대표 선거','주민 여러분의 적극 참여 바랍니다 ^^',TO_TIMESTAMP('2023-08-02 16:10', 'YYYY-MM-DD HH24:MI'),12,'N');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,1,1,'103동 대표 선거','주민 여러분의 적극 참여 바랍니다 ^^',TO_TIMESTAMP('2023-08-02 16:20', 'YYYY-MM-DD HH24:MI'),13,'N');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,2,1,'엘리베이터 교체 공지','8월 16일부터 9월 15일까지, 한 달간 엘리베이터 교체가 진행될 예정입니다.',TO_TIMESTAMP('2023-08-03 13:30', 'YYYY-MM-DD HH24:MI'),77,'N');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,3,1,'관리비 결제 공지','미납된 관리비가 있는 세대는 빠른 시일 내 결제 부탁드립니다.',TO_TIMESTAMP('2023-08-03 14:30', 'YYYY-MM-DD HH24:MI'),15,'N');
INSERT INTO NOTICE (NO,NOTICE_CNO,WRITER_NO,TITLE,CONTENT,ENROLL_DATE,HIT,IMPORTANT_YN) VALUES (SEQ_NOTICE_NO.NEXTVAL,4,1,'푸리미엄 아파트 벼룩시장 개최 예정입니다','자세한 공지는 추후 등록하겠습니다.',TO_TIMESTAMP('2023-08-03 15:30', 'YYYY-MM-DD HH24:MI'),20,'N');


--시설
--관리
--행사

-- 댓글
INSERT INTO REPLY (NO,BOARD_NO,WRITER_NO,REPLY_NO,CONTENT) VALUES (SEQ_REPLY_NO.NEXTVAL,1,2,NULL,'저도 반가워요 ㅎㅎ');
INSERT INTO REPLY (NO,BOARD_NO,WRITER_NO,REPLY_NO,CONTENT) VALUES (SEQ_REPLY_NO.NEXTVAL,1,1,1,'잘 부탁드려요~~');


--좋아요 게시물
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (1, 1);
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (1, 2);
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (1, 3);
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (1, 4);
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (1, 5);
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (1, 6);
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (1, 7);
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (1, 8);
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (1, 9);
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (1, 10);
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (2, 1);
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (2, 2);
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (2, 3);
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (2, 4);
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (2, 5);
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (3, 1);
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (4, 1);
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (5, 1);
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (6, 1);
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (7, 1);
INSERT INTO LOVE (MEMBER_NO, BOARD_NO) VALUES (8, 1);




--투표
INSERT INTO VOTE (NOTICE_NO,TITLE,END_DATE,DUP_YN) VALUES (10,'101동 대표 선거','2023-09-01','N');
--투표항목
INSERT INTO VOTE_CANDIDATE (NO,NOTICE_NO,NAME) VALUES (SEQ_VOTE_CANDIDATE_NO.NEXTVAL,10,'심일용');
INSERT INTO VOTE_CANDIDATE (NO,NOTICE_NO,NAME) VALUES (SEQ_VOTE_CANDIDATE_NO.NEXTVAL,10,'심둘용');
INSERT INTO VOTE_CANDIDATE (NO,NOTICE_NO,NAME) VALUES (SEQ_VOTE_CANDIDATE_NO.NEXTVAL,10,'심셋용');
--개인투표내역
INSERT INTO PERSONAL_VOTE (NO,MEMBER_NO,VOTE_LIST_NO) VALUES (SEQ_PERSONAL_VOTE_NO.NEXTVAL,1,1);
INSERT INTO PERSONAL_VOTE (NO,MEMBER_NO,VOTE_LIST_NO) VALUES (SEQ_PERSONAL_VOTE_NO.NEXTVAL,2,1);
INSERT INTO PERSONAL_VOTE (NO,MEMBER_NO,VOTE_LIST_NO) VALUES (SEQ_PERSONAL_VOTE_NO.NEXTVAL,3,1);
INSERT INTO PERSONAL_VOTE (NO,MEMBER_NO,VOTE_LIST_NO) VALUES (SEQ_PERSONAL_VOTE_NO.NEXTVAL,4,2);
INSERT INTO PERSONAL_VOTE (NO,MEMBER_NO,VOTE_LIST_NO) VALUES (SEQ_PERSONAL_VOTE_NO.NEXTVAL,5,2);
INSERT INTO PERSONAL_VOTE (NO,MEMBER_NO,VOTE_LIST_NO) VALUES (SEQ_PERSONAL_VOTE_NO.NEXTVAL,6,2);
INSERT INTO PERSONAL_VOTE (NO,MEMBER_NO,VOTE_LIST_NO) VALUES (SEQ_PERSONAL_VOTE_NO.NEXTVAL,7,3);
INSERT INTO PERSONAL_VOTE (NO,MEMBER_NO,VOTE_LIST_NO) VALUES (SEQ_PERSONAL_VOTE_NO.NEXTVAL,8,3);
INSERT INTO PERSONAL_VOTE (NO,MEMBER_NO,VOTE_LIST_NO) VALUES (SEQ_PERSONAL_VOTE_NO.NEXTVAL,9,3);


-- 식단
INSERT INTO DIET VALUES(SEQ_DIET_NO.NEXTVAL, '차조밥,조개국,불고기,시금치나물,배추김치', '열량 642kcal,당질 97g,단백질 31g,지질 13g', 'menu1.PNG');
INSERT INTO DIET VALUES(SEQ_DIET_NO.NEXTVAL, '보리밥,김치찌개,잡채,김구이,오이생채,깍두기', '열량 679kcal,당질 121g,단백질 20g,지질 14g', 'menu2.PNG');
INSERT INTO DIET VALUES(SEQ_DIET_NO.NEXTVAL, '현미밥,냉이된장국,임연수구이,두부조림,마늘쫑무침,배추김치', '열량 645kcal,당질 98g,단백질 32g,지질 15g', 'menu3.PNG');
INSERT INTO DIET VALUES(SEQ_DIET_NO.NEXTVAL, '수수밥,근대국,삼치간장조림,취나물볶음,총각김치', '열량 619kcal,당질 120g,단백질 23g,지질 6g', 'menu4.PNG');
INSERT INTO DIET VALUES(SEQ_DIET_NO.NEXTVAL, '김치볶음밥,무국,고추멸치볶음,감자샐러드,나박김치', '열량 646kcal,당질 118g,단백질 19g,지질 12g', 'menu5.PNG');
INSERT INTO DIET VALUES(SEQ_DIET_NO.NEXTVAL, '콩밥,쇠고기버섯전골,달걀채소말이,도라지생채,열무김치', '열량 616kcal,당질 101g,단백질 25g,지질 13g', 'menu6.PNG');
INSERT INTO DIET VALUES(SEQ_DIET_NO.NEXTVAL, '채소샌드위치,우유,달걀후라이,오렌지', '열량 637kcal,당질 68g,단백질 26g,지질 30g', 'menu7.PNG');

-- 조식
INSERT INTO BREAKFAST VALUES(SEQ_BREAKFAST_NO.NEXTVAL, 1, SYSDATE);
INSERT INTO BREAKFAST VALUES(SEQ_BREAKFAST_NO.NEXTVAL, 2, SYSDATE + 1);
INSERT INTO BREAKFAST VALUES(SEQ_BREAKFAST_NO.NEXTVAL, 3, SYSDATE + 2);
INSERT INTO BREAKFAST VALUES(SEQ_BREAKFAST_NO.NEXTVAL, 4, SYSDATE + 3);
INSERT INTO BREAKFAST VALUES(SEQ_BREAKFAST_NO.NEXTVAL, 5, SYSDATE + 4);
INSERT INTO BREAKFAST VALUES(SEQ_BREAKFAST_NO.NEXTVAL, 6, SYSDATE + 5);
INSERT INTO BREAKFAST VALUES(SEQ_BREAKFAST_NO.NEXTVAL, 7, SYSDATE + 6);
INSERT INTO BREAKFAST VALUES(SEQ_BREAKFAST_NO.NEXTVAL, 1, SYSDATE + 7);
INSERT INTO BREAKFAST VALUES(SEQ_BREAKFAST_NO.NEXTVAL, 2, SYSDATE + 8);
INSERT INTO BREAKFAST VALUES(SEQ_BREAKFAST_NO.NEXTVAL, 3, SYSDATE + 9);

-- 조식 신청 내역
INSERT INTO MEAL_RESERVATION VALUES(SEQ_MEAL_RESERVATION_NO.NEXTVAL, 1, 1, 'Y');
INSERT INTO MEAL_RESERVATION VALUES(SEQ_MEAL_RESERVATION_NO.NEXTVAL, 1, 2, 'Y');
INSERT INTO MEAL_RESERVATION VALUES(SEQ_MEAL_RESERVATION_NO.NEXTVAL, 2, 1, 'Y');
INSERT INTO MEAL_RESERVATION VALUES(SEQ_MEAL_RESERVATION_NO.NEXTVAL, 2, 2, 'Y');
INSERT INTO MEAL_RESERVATION VALUES(SEQ_MEAL_RESERVATION_NO.NEXTVAL, 3, 1, 'Y');
INSERT INTO MEAL_RESERVATION VALUES(SEQ_MEAL_RESERVATION_NO.NEXTVAL, 4, 1, 'Y');
INSERT INTO MEAL_RESERVATION VALUES(SEQ_MEAL_RESERVATION_NO.NEXTVAL, 5, 1, 'Y');
INSERT INTO MEAL_RESERVATION VALUES(SEQ_MEAL_RESERVATION_NO.NEXTVAL, 6, 1, 'Y');
INSERT INTO MEAL_RESERVATION VALUES(SEQ_MEAL_RESERVATION_NO.NEXTVAL, 7, 1, 'Y');
INSERT INTO MEAL_RESERVATION VALUES(SEQ_MEAL_RESERVATION_NO.NEXTVAL, 8, 1, 'Y');
INSERT INTO MEAL_RESERVATION VALUES(SEQ_MEAL_RESERVATION_NO.NEXTVAL, 9, 1, 'N');
INSERT INTO MEAL_RESERVATION VALUES(SEQ_MEAL_RESERVATION_NO.NEXTVAL, 10, 1, 'N');



COMMIT;

